name: Windows

on:
  push:
    paths-ignore:
      - '**.md'
   

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create and push tag
      id: create_tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        TAG_NAME=$(git rev-parse --short HEAD)
        echo "Pushing tag $TAG_NAME"
        git tag $TAG_NAME
        git push origin $TAG_NAME
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
      shell: bash
    - name: configure
      run: |
        cd Build 
        cmake -G "Visual Studio 17 2022" -A x64 ..
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: build
      run: |
        msbuild Build/ALL_BUILD.vcxproj -p:Configuration=Release -p:Platform=x64 -m
    - name: deploy
      run: |
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DLLs/FrontPanelUSB-DriverOnly-4.5.5.exe open-ephys
        cp -r ../Resources/DLLs/FTD3XXDriver_WHQLCertified_1.3.0.10_Installer.exe open-ephys
        cp ../LICENSE open-ephys
        cp C:/Windows/System32/msvcp140.dll open-ephys
        cp C:/Windows/System32/vcruntime140.dll open-ephys
        cp C:/Windows/System32/vcruntime140_1.dll open-ephys
        powershell Compress-Archive -Path "open-ephys" -DestinationPath open-ephys-windows.zip
        
        cd open-ephys
        rm -f msvcp140.dll vcruntime140.dll vcruntime140_1.dll
        cd ../../Resources/Installers/Windows
        iscc "windows_installer_script.iss"
      shell: bash
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: Build/open-ephys-windows.zip,Resources/Installers/Windows/Open-Ephys_Installer.exe
        tag: ${{ steps.create_tag.outputs.TAG_NAME }}
